name: FridayThe14th
main: com.au5tie.f13.FridayThe13thPlugin
version: ${project.version}
description: Friday the 13th
author: Au5tie
website: http://f13mc.com
load: POSTWORLD
softdepend: [Multiverse-Core, Multiworld, HolographicDisplays, ActionBarAPI, LanguageAPI, SidebarAPI, ProtocolLib, CorpseReborn, CustomSoundManagerAPI]
api-version: 1.16
commands:
  f13:
    description: Friday the 13th Player Commands.
  tobsetup:
    description: Tobnet Engine setup command.
  tobadmin:
    description: Tobnet Engine admin command.
permissions:
  Pie.*:
    description: Gives access to all commands
    children:
      Pie.admin: true
      Pie.user: true
    default: op
  Pie.user:
    description: User level permissions to Tobnet
    default: true